### ISSUE TITLE
Review !

### ISSUE THREAD

**Issue by Christiantaguejou** [PolytechLyon/pattern-strategy-lombardo-taguejou-tp3#1]

**Comment by k33g** [comment]
Bonjour @Christiantaguejou 
En général lorsque l'on utilise un outil comme GitHub ou GitLab ou autre, il est de bon ton d'accompagner l'assignation par un petit message (bonjour déjà c'est pas mal)

- Exercice 0, 1 et 2: les explications sont un peu courtes 
- Exercice 3: bonne idée pour l'affichage
- Votre avis sur le pattern: ok (mais j'aurais aimé que vous alliez un peu plus dans le détail)
- Les cas d'utilisation: même remarque

**Comment by Christiantaguejou** [comment]
Bonsoir @k33g 
Veuillez m'excuser pour cet oubli.
J'ai modifié mon rapport sur les points que vous avez souligné.

**Comment by k33g** [comment]
@Christiantaguejou ok
pas besoin de mettre **New** 😉 avec les diffs je peux voir ce que vous avez ajouté
https://github.com/PolytechLyon/pattern-strategy-lombardo-taguejou-tp3/commit/61c9299c4171218132ea8ae1ddceaf20254c66b2

⚠️ faites attention à votre orthographe

**Comment by Florian06370** [comment]
Bonjour, le rapport a été relu et corrigé.
Merci
